#!/bin/bash

SIM_CALL=$1
SIM_DIR="./simulation"

if [[ -d "$SIM_DIR" ]]; then
    rm -rf ${SIM_DIR}
fi

mkdir ${SIM_DIR}
case "${SIM_CALL}" in
    matrix)
        cp -r ./source/Matrix/* ${SIM_DIR}
        cd ${SIM_DIR} && make
        ;;
    linkedlist)
        cp -r ./source/LinkedList/* ${SIM_DIR}
        cd ${SIM_DIR} && make
        ;;
    projectile-3d)
        cp -r ./source/Projectile/3d/* ${SIM_DIR}
        cd ${SIM_DIR} && make
        ;;
    projectile-2d)
        cp -r ./source/Projectile/2d/* ${SIM_DIR}
        cd ${SIM_DIR} && make
        ;;
    *)
        if [[ -z "${SIM_CALL}" ]]; then
            echo "Enter a simulation name"
            exit 0
        fi
        echo "No such simulation found"
        ;;
esac
